name: Docker

on:
 workflow_call:

jobs:
 docker:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0
      
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: marceloalmeidadesouza
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3
      uses: docker/build-push-action@v3.3.0
      with:
       context: . #caminho dos arquivos
       file: ./Dockerfile # caminho do dockerfile
       push: true # faz o push da image para um dado lugar
       tags: marceloalmeidadesouza/go_ci:${{github.ref_name}}
    
