name: Entrega continua

on:
  workflow_call:
  
jobs:
   ec2:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        # Artifact name
        name: programa
    - uses: actions/checkout@v3
    - name: Deploy to staging server
      uses: easingthemes/ssh-deploy@v4.0.5
      with:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        # Remote host
        REMOTE_HOST: ${{secrets.SSH_PRIVATE_KEY}}
        # Remote user
        REMOTE_USER: ${{secrets.SSH_PRIVATE_KEY}}
        TARGET: ${{secrets.SSH_PRIVATE_KEY}}
        EXCLUDE: "/dist/, /node_modules/"
      
