name: Entrega continua

on:
  workflow_call:
  
jobs:
  ec2:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        # Artifact name
        name: programa
    - uses: actions/checkout@v3
    - name: Deploy to staging server
      uses: easingthemes/ssh-deploy@v4.0.5
      with:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        # Remote host
        REMOTE_HOST: ${{secrets.REMOTE_HOST}}
        # Remote user
        REMOTE_USER: ${{secrets.REMOTE_USER}}
        TARGET: /home/${{secrets.REMOTE_USER}}
        EXCLUDE: "postgres-data"
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: 22
        script: |
          export HOST=${{ secrets.DBHOST }}
          export USER=${{ secrets.DBUSER }}
          export PASSWORD=${{ secrets.DBPASSWORD }}
          export DBNAME=${{ secrets.DBNAME }}
          export DBPORT=${{ secrets.DBPORT }}
          export PORT=8000
      
