name: Entrega continua

on:
  workflow_call:
  
jobs:
   docker:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        # Artifact name
        name: programa
      - uses: actions/checkout@v3
