# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ['no*run']
  pull_request:
    branches: ['no*run']
    
jobs:
  test:
    runs-on: ${{matrix.os}}
    env:
      HOST: localhost
      DBPORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.18', '>=1.19']
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{matrix.go_version}}

    - name: Build-DB
      run: docker-compose build

    - name: Create-DB
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: programa # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: main
        
  docker:
    needs: build
    uses: './.github/workflows/Docker.yml'
    secrets: inherit
    
  #deploy_ec2: # Continuous deploy
    #needs: build
    #uses: './.github/workflows/ec2.yml'
    #secrets: inherit
    
  deploy_ecs: # Continuous deploy
    needs: docker
    uses: './.github/workflows/ecs.yml'
    secrets: inherit
